// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Schedule.Infrastructure.Persistence;

#nullable disable

namespace Schedule.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ScheduleDbContext))]
    [Migration("20260925154137_MakeStructureRefIdNullable")]
    partial class MakeStructureRefIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Schedule.Domain.Entities.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("StructureRefId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentRefId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherRefId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StructureRefId", "ScheduledAt");

                    b.HasIndex("StudentRefId", "ScheduledAt");

                    b.HasIndex("TeacherRefId", "ScheduledAt");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("Schedule.Domain.Entities.OfficeHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid?>("StructureRefId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherRefId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StructureRefId", "DayOfWeek");

                    b.HasIndex("TeacherRefId", "DayOfWeek");

                    b.ToTable("OfficeHours");
                });
#pragma warning restore 612, 618
        }
    }
}
